version: '3'
services:
    meilisearch:
        image: getmeili/meilisearch:v1.4
        ports:
        - 7700:7700
        volumes:
        - $(pwd)/data.ms:/data.ms\
        environment:
          MEILI_MASTER_KEY: 'MASTER_KEY'