version: '2'
services:
  pusher:
    image: wisecity/prometheus-pusher
    network_mode: host
    environment:
      PUSH_GATEWAY: http://pushgateway.doamin.com
      PORT: 9101
      TZ: Asia/Shanghai
    volumes:
    - ./prometheus.yml:/etc/prom-conf/prometheus.yml
    entrypoint:
    - /bin/prometheus_pusher
    - -config.file
    - /etc/prom-conf/prometheus.yml
