version: '3.7'
#better deploy redis and postgresql to another server for disaster recovery
services:
  sentry-web:
    image: sentry:9.1
    container_name: sentry-web
    hostname: sentry-web
    restart: always
    ports:
      - '9000:9000'
    env_file:
      - .env
    command: "sentry run web"
    networks:
      - sentry
    volumes:
      - './data/sentry:/var/lib/sentry/files'

  sentry-cron:
    image: sentry:9.1
    container_name: sentry-cron
    hostname: sentry-cron
    restart: always
    env_file:
      - .env
    command: "sentry run cron"
    networks:
      - sentry
    volumes:
      - './data/sentry:/var/lib/sentry/files'

  sentry-worker:
    image: sentry:9.1
    container_name: sentry-worker
    hostname: sentry-worker
    restart: always
    env_file:
      - .env
    command: "sentry run worker"
    networks:
      - sentry
    volumes:
      - './data/sentry:/var/lib/sentry/files'

networks:
  sentry:
    driver: bridge